#!/bin/bash

echo "Collecting Performance Events' Counts on Intel Haswell Multicore Server"

DIR=()  # specify path to application directory

#list benchmark applications

BENCHMARKS=()

BNUM=${#BENCHMARKS[@]}

for (( ACOUNT=0; ACOUNT<4; ACOUNT++))
do

for (( BCOUNT=0; BCOUNT<${BNUM}; BCOUNT++ ))
do 
touch perfcounts_${BENCHMARKS[$BCOUNT]}_$ACOUNT
touch output_${BENCHMARKS[$BCOUNT]}_$ACOUNT
done

done

for (( ACOUNT=0; ACOUNT<4; ACOUNT++))
do
for (( BCOUNT=0; BCOUNT<${BNUM}; BCOUNT++ ))
do
   EXE=$DIR
   EXE+="/"
   EXE+=${BENCHMARKS[$BCOUNT]} 
  
  LIKWID_PERF_EVENTS=(
BR_INST_EXEC_ALL_BRANCHES:PMC0,BR_MISP_EXEC_ALL_BRANCHES:PMC1,BR_INST_RETIRED_ALL_BRANCHES:PMC2,BR_MISP_RETIRED_ALL_BRANCHES:PMC3,UNCORE_CLOCK:UBOXFIX,CBOX_CLOCKTICKS:CBOX0C1,SBOX_CLOCKTICKS:SBOX0C1,WBOX_CLOCKTICKS:WBOX1,BBOX_CLOCKTICKS:BBOX0C1,DRAM_CLOCKTICKS:MBOX0C1,PBOX_CLOCKTICKS:PBOX1,RBOX_CLOCKTICKS:RBOX0C1,QBOX_CLOCKTICKS:QBOX0C1,LLC_LOOKUP_DATA_READ:STATE,SNOOPS_RSP_AFTER_DATA_LOCAL:BBOX0C0,SNOOPS_RSP_AFTER_DATA_REMOTE:BBOX0C2,RXL_FLITS_G1_DRS_DATA:QBOX0C0,RXL_FLITS_G1_DRS_NONDATA:QBOX0C2,RXL_FLITS_G2_NCB_DATA:QBOX0C3,RXL_FLITS_G2_NCB_NONDATA:QBOX1C0,RXL_FLITS_G0_DATA:QBOX1C2,RXL_FLITS_G0_NON_DATA:QBOX1C3,TXL_FLITS_G0_DATA:QBOX0FIX2,TXL_FLITS_G0_NON_DATA:QBOX0FIX0,TXL_FLITS_G1_DRS_DATA:QBOX1FIX1,TXL_FLITS_G1_DRS_NONDATA:QBOX0FIX1,TXL_FLITS_G2_NCB_DATA:QBOX1FIX2,PWR_PKG_ENERGY:PWR0,PWR_PP0_ENERGY:PWR1,PWR_DRAM_ENERGY:PWR3,CPU_CLK_UNHALTED_ANY:FIXC1,CPU_CLK_UNHALTED_REF:FIXC2,
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT 

LIKWID_PERF_EVENTS1=(
CPU_CLOCK_UNHALTED_THREAD_P:PMC0,CPU_CLOCK_UNHALTED_THREAD_P_ANY:PMC1,CPU_CLOCK_UNHALTED_REF_XCLK:PMC2,CPU_CLOCK_UNHALTED_REF_XCLK_ANY:PMC3,TXL_FLITS_G2_NCB_NONDATA:QBOX1FIX2,CPU_CLK_UNHALTED_CORE:FIXC1,MEMORY_PHASE_SHEDDING_CYCLES:WBOX0,POWER_CHANNEL_DLLOFF:MBOX5C1,POWER_CHANNEL_PPD:MBOX5C2,HA_R2_BL_CREDITS_EMPTY_LO_HA0:RBOX0C0,HA_R2_BL_CREDITS_EMPTY_LO_HA1:RBOX1C0

)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS1  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT
LIKWID_PERF_EVENTS2=(
CPU_CLOCK_THREAD_UNHALTED_ONE_THREAD_ACTIVE:PMC0,CPU_CLOCK_UNHALTED_TOTAL_CYCLES:PMC1,L2_RQSTS_ALL_DEMAND_DATA_RD_MISS:PMC2,L2_RQSTS_ALL_DEMAND_DATA_RD_HIT:PMC3,HA_R2_BL_CREDITS_EMPTY_LO_R2_NCB:RBOX0C0,HA_R2_BL_CREDITS_EMPTY_LO_R2_NCS:RBOX1C0
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS2  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS3=(
L2_RQSTS_ALL_DEMAND_DATA_RD:PMC0,OFFCORE_REQUESTS_OUTSTANDING_DEMAND_DATA_RD:PMC1,OFFCORE_REQUESTS_OUTSTANDING_ALL_DATA_RD:PMC2,OFFCORE_REQUESTS_OUTSTANDING_CYCLES_WITH_DEMAND_DATA_RD:PMC3,HA_R2_BL_CREDITS_EMPTY_HI_HA0:RBOX1C1,HA_R2_BL_CREDITS_EMPTY_HI_HA1:RBOX0C1
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS3  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS4=(
OFFCORE_REQUESTS_OUTSTANDING_CYCLES_WITH_DATA_RD:PMC0,OFFCORE_REQUESTS_OUTSTANDING_DEMAND_DATA_RD_C6:PMC1,UOPS_EXECUTED_PORT_DATA_PORTS:PMC2,OFFCORE_REQUESTS_DEMAND_DATA_RD:PMC3,HA_R2_BL_CREDITS_EMPTY_HI_R2_NCB:RBOX0C1,HA_R2_BL_CREDITS_EMPTY_HI_R2_NCS:RBOX1C1
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS4  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS5=(
OFFCORE_REQUESTS_ALL_DATA_RD:PMC0,L2_TRANS_DEMAND_DATA_RD:PMC1,OFFCORE_RESPONSE_0_DMND_DATA_RD_ANY:PMC2,OFFCORE_RESPONSE_0_PF_L2_DATA_RD_ANY:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS5  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS6=(
OFFCORE_RESPONSE_0_PF_L3_DATA_RD_ANY:PMC0,OFFCORE_RESPONSE_1_DMND_DATA_RD_ANY:PMC1,OFFCORE_RESPONSE_1_PF_L2_DATA_RD_ANY:PMC2,OFFCORE_RESPONSE_1_PF_L3_DATA_RD_ANY:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS6  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS7=(
CPU_CLOCK_UNHALTED_THREAD_P:PMC0,CPU_CLOCK_UNHALTED_THREAD_P_ANY:PMC1,CPU_CLOCK_UNHALTED_REF_XCLK:PMC2,CPU_CLOCK_UNHALTED_REF_XCLK_ANY:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS7  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS8=(
CPU_CLOCK_THREAD_UNHALTED_ONE_THREAD_ACTIVE:PMC0,CPU_CLOCK_UNHALTED_TOTAL_CYCLES:PMC1,ICACHE_HIT:PMC2,ICACHE_MISSES:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS8  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS9=(
ICACHE_ACCESSES:PMC0,ICACHE_IFETCH_STALL:PMC1,L2_RQSTS_ALL_DEMAND_DATA_RD_MISS:PMC2,L2_RQSTS_ALL_DEMAND_DATA_RD_HIT:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS9  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS10=(
L2_RQSTS_ALL_DEMAND_DATA_RD:PMC0,L2_RQSTS_RFO_HIT:PMC1,L2_RQSTS_RFO_MISS:PMC2,L2_RQSTS_ALL_RFO:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS10  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS11=(
L2_RQSTS_CODE_RD_HIT:PMC0,L2_RQSTS_CODE_RD_MISS:PMC1,L2_RQSTS_ALL_DEMAND_MISS:PMC2,L2_RQSTS_ALL_DEMAND_REFERENCES:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS11  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS12=(
L2_RQSTS_ALL_CODE_RD:PMC0,L2_RQSTS_L2_PF_HIT:PMC1,L2_RQSTS_L2_PF_MISS:PMC2,L2_RQSTS_ALL_PF:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS12  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS13=(
L2_RQSTS_MISS:PMC0,L2_RQSTS_REFERENCES:PMC1,L2_DEMAND_RQST_WB_HIT:PMC2,CYCLE_ACTIVITY_CYCLES_L2_PENDING:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS13  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS14=(
CYCLE_ACTIVITY_STALLS_L2_PENDING:PMC0,PAGE_WALKER_LOADS_DTLB_L2:PMC1,PAGE_WALKER_LOADS_ITLB_L2:PMC2,PAGE_WALKER_LOADS_EPT_DTLB_L2:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS14  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS15=(
PAGE_WALKER_LOADS_EPT_ITLB_L2:PMC0,MEM_LOAD_UOPS_RETIRED_L2_HIT:PMC1,MEM_LOAD_UOPS_RETIRED_L2_MISS:PMC2,MEM_LOAD_UOPS_RETIRED_L2_ALL:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS15 $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS16=(
L2_TRANS_DEMAND_DATA_RD:PMC0,L2_TRANS_RFO:PMC1,L2_TRANS_CODE_RD:PMC2,L2_TRANS_ALL_PF:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS16  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS17=(
L2_TRANS_L1D_WB:PMC0,L2_TRANS_L2_FILL:PMC1,L2_TRANS_L2_WB:PMC2,L2_TRANS_ALL_REQUESTS:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS17  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS18=(
L2_LINES_IN_I:PMC0,L2_LINES_IN_S:PMC1,L2_LINES_IN_E:PMC2,L2_LINES_IN_ALL:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS18  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS19=(
L2_LINES_OUT_DEMAND_CLEAN:PMC0,L2_LINES_OUT_DEMAND_DIRTY:PMC1,OFFCORE_RESPONSE_0_PF_L2_DATA_RD_ANY:PMC2,OFFCORE_RESPONSE_0_PF_L2_RFO_ANY:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS19 $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS20=(
OFFCORE_RESPONSE_0_PF_L2_CODE_RD_ANY:PMC0,OFFCORE_RESPONSE_1_PF_L2_DATA_RD_ANY:PMC1,OFFCORE_RESPONSE_1_PF_L2_RFO_ANY:PMC2,OFFCORE_RESPONSE_1_PF_L2_CODE_RD_ANY:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS20  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS21=(
PAGE_WALKER_LOADS_DTLB_L3:PMC0,PAGE_WALKER_LOADS_ITLB_L3:PMC1,PAGE_WALKER_LOADS_EPT_DTLB_L3:PMC2,PAGE_WALKER_LOADS_EPT_ITLB_L3:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS21  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS22=(
MEM_LOAD_UOPS_RETIRED_L3_HIT:PMC0,MEM_LOAD_UOPS_RETIRED_L3_MISS:PMC1,MEM_LOAD_UOPS_RETIRED_L3_ALL:PMC2,MEM_LOAD_UOPS_L3_HIT_RETIRED_XSNP_MISS:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS22  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS23=(
MEM_LOAD_UOPS_L3_HIT_RETIRED_XSNP_HIT:PMC0,MEM_LOAD_UOPS_L3_HIT_RETIRED_XSNP_HITM:PMC1,MEM_LOAD_UOPS_L3_HIT_RETIRED_XSNP_NONE:PMC2,MEM_LOAD_UOPS_L3_MISS_RETIRED_LOCAL_DRAM:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS23  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS24=(
MEM_LOAD_UOPS_L3_MISS_RETIRED_REMOTE_DRAM:PMC0,MEM_LOAD_UOPS_L3_MISS_RETIRED_REMOTE_HITM:PMC1,MEM_LOAD_UOPS_L3_MISS_RETIRED_REMOTE_FWD:PMC2,OFFCORE_RESPONSE_0_PF_L3_DATA_RD_ANY:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS24  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS25=(
OFFCORE_RESPONSE_0_PF_L3_RFO_ANY:PMC0,OFFCORE_RESPONSE_0_PF_L3_CODE_RD_ANY:PMC1,OFFCORE_RESPONSE_1_PF_L3_DATA_RD_ANY:PMC2,OFFCORE_RESPONSE_1_PF_L3_RFO_ANY:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS25  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS26=(
OFFCORE_RESPONSE_1_PF_L3_CODE_RD_ANY:PMC0,MISALIGN_MEM_REF_LOADS:PMC1,MISALIGN_MEM_REF_STORES:PMC2,MISALIGN_MEM_REF_ANY:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS26  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS27=(
TX_MEM_ABORT_CONFLICT:PMC0,TX_MEM_ABORT_CAPACITY_WRITE:PMC1,TX_MEM_ABORT_HLE_STORE_TO_ELIDED_LOCK:PMC2,TX_MEM_ABORT_HLE_ELISION_BUFFER_NOT_EMPTY:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS27  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS28=(
TX_MEM_ABORT_HLE_ELISION_BUFFER_MISMATCH:PMC0,TX_MEM_ABORT_HLE_ELISION_BUFFER_UNSUPPORTED_ALIGNMENT:PMC1,TX_MEM_HLE_ELISION_BUFFER_FULL:PMC2,CYCLE_ACTIVITY_CYCLES_MEM_ANY:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS28  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS29=(
CYCLE_ACTIVITY_STALLS_MEM_ANY:PMC0,PAGE_WALKER_LOADS_DTLB_MEMORY:PMC1,PAGE_WALKER_LOADS_ITLB_MEMORY:PMC2,PAGE_WALKER_LOADS_EPT_DTLB_MEMORY:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS29  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS30=(
PAGE_WALKER_LOADS_EPT_ITLB_MEMORY:PMC0,MACHINE_CLEARS_MEMORY_ORDERING:PMC1,MEM_UOPS_RETIRED_LOADS:PMC2,MEM_UOPS_RETIRED_STORES:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS30  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS31=(
MEM_UOPS_RETIRED_ALL:PMC0,MEM_UOPS_RETIRED_LOADS_STLB_MISS:PMC1,MEM_UOPS_RETIRED_STORES_STLB_MISS:PMC2,MEM_UOPS_RETIRED_LOADS_LOCK:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS31  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS32=(
MEM_UOPS_RETIRED_STORES_LOCK:PMC0,MEM_UOPS_RETIRED_LOADS_SPLIT:PMC1,MEM_UOPS_RETIRED_STORES_SPLIT:PMC2,MEM_LOAD_UOPS_RETIRED_L1_HIT:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS32  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS33=(
MEM_LOAD_UOPS_RETIRED_L1_MISS:PMC0,MEM_LOAD_UOPS_RETIRED_L1_ALL:PMC1,MEM_LOAD_UOPS_RETIRED_ALL_MISS:PMC2,MEM_LOAD_UOPS_RETIRED_ALL_HIT:PMC3

)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS33  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS34=(
MEM_LOAD_UOPS_RETIRED_ALL_ALL:PMC0,IIO_CREDIT_PRQ_QPI0:PBOX0,IIO_CREDIT_PRQ_QPI1:PBOX1,IIO_CREDIT_ISOCH_QPI0:PBOX2,IIO_CREDIT_ISOCH_QPI1:PBOX3,IGR_NO_CREDIT_CYCLES_BL_QPI1:BBOX1C3,IGR_NO_CREDIT_CYCLES_BL_QPI0:BBOX0C1,IGR_NO_CREDIT_CYCLES_AD_QPI2:BBOX0C0,IGR_NO_CREDIT_CYCLES_BL_QPI2:BBOX1C0,UOPS_ISSUED_ANY:PMC3,UOPS_ISSUED_FLAGS_MERGE:PMC1,UOPS_ISSUED_SLOW_LEA:PMC2
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS34  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS35=(
UOPS_ISSUED_SINGLE_MUL:PMC0,UOPS_ISSUED_USED_CYCLES:PMC1,UOPS_ISSUED_STALL_CYCLES:PMC2,UOPS_ISSUED_TOTAL_CYCLES:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS35  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS36=(
UOPS_ISSUED_CORE_USED_CYCLES:PMC0,UOPS_ISSUED_CORE_STALL_CYCLES:PMC1,UOPS_ISSUED_CORE_TOTAL_CYCLES:PMC2,ARITH_DIVIDER_UOPS:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS36  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS37=(
IDQ_MITE_UOPS:PMC0,IDQ_DSB_UOPS:PMC1,IDQ_MS_DSB_UOPS:PMC2,IDQ_MS_MITE_UOPS:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS37  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS38=(
IDQ_MS_UOPS:PMC0,IDQ_ALL_DSB_CYCLES_ANY_UOPS:PMC1,IDQ_ALL_DSB_CYCLES_4_UOPS:PMC2,IDQ_ALL_MITE_CYCLES_ANY_UOPS:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS38  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS39=(
IDQ_ALL_MITE_CYCLES_4_UOPS:PMC0,IDQ_MITE_ALL_UOPS:PMC1,IDQ_UOPS_NOT_DELIVERED_CORE:PMC2,IDQ_UOPS_NOT_DELIVERED_CYCLES_0_UOPS_DELIV_CORE:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS39  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS40=(
IDQ_UOPS_NOT_DELIVERED_CYCLES_LE_1_UOP_DELIV_CORE:PMC0,IDQ_UOPS_NOT_DELIVERED_CYCLES_LE_2_UOP_DELIV_CORE:PMC1,IDQ_UOPS_NOT_DELIVERED_CYCLES_LE_3_UOP_DELIV_CORE:PMC2,IDQ_UOPS_NOT_DELIVERED_CYCLES_FE_WAS_OK:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS40  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS41=(
UOPS_EXECUTED_PORT_PORT_0:PMC0,UOPS_EXECUTED_PORT_PORT_1:PMC1,UOPS_EXECUTED_PORT_PORT_2:PMC2,UOPS_EXECUTED_PORT_PORT_3:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS41  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS42=(
UOPS_EXECUTED_PORT_PORT_4:PMC0,UOPS_EXECUTED_PORT_PORT_5:PMC1,UOPS_EXECUTED_PORT_PORT_6:PMC2,UOPS_EXECUTED_PORT_PORT_7:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS42  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS43=(
UOPS_EXECUTED_PORT_PORT_0_CORE:PMC0,UOPS_EXECUTED_PORT_PORT_1_CORE:PMC1,UOPS_EXECUTED_PORT_PORT_2_CORE:PMC2,UOPS_EXECUTED_PORT_PORT_3_CORE:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS43  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS44=(
UOPS_EXECUTED_PORT_PORT_4_CORE:PMC0,UOPS_EXECUTED_PORT_PORT_5_CORE:PMC1,UOPS_EXECUTED_PORT_PORT_6_CORE:PMC2,UOPS_EXECUTED_PORT_PORT_7_CORE:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS44  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS45=(
UOPS_EXECUTED_PORT_ARITH_PORTS:PMC0,UOPS_EXECUTED_PORT_ARITH_PORTS_CORE:PMC1,UOPS_EXECUTED_PORT_DATA_PORTS:PMC2,LSD_UOPS:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS45  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS46=(
LSD_CYCLES_4_UOPS:PMC0,UOPS_EXECUTED_THREAD:PMC1,UOPS_EXECUTED_USED_CYCLES:PMC2,UOPS_EXECUTED_STALL_CYCLES:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS46  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS47=(
UOPS_EXECUTED_TOTAL_CYCLES:PMC0,UOPS_EXECUTED_CYCLES_GE_1_UOPS_EXEC:PMC1,UOPS_EXECUTED_CYCLES_GE_2_UOPS_EXEC:PMC2,UOPS_EXECUTED_CYCLES_GE_3_UOPS_EXEC:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS47  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS48=(
UOPS_EXECUTED_CYCLES_GE_4_UOPS_EXEC:PMC0,UOPS_EXECUTED_CORE:PMC1,UOPS_EXECUTED_CORE_USED_CYCLES:PMC2,UOPS_EXECUTED_CORE_STALL_CYCLES:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS48  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS49=(
UOPS_EXECUTED_CORE_TOTAL_CYCLES:PMC0,UOPS_EXECUTED_CORE_CYCLES_GE_1_UOPS_EXEC:PMC1,UOPS_EXECUTED_CORE_CYCLES_GE_2_UOPS_EXEC:PMC2,UOPS_EXECUTED_CORE_CYCLES_GE_3_UOPS_EXEC:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS49  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS50=(
UOPS_EXECUTED_CORE_CYCLES_GE_4_UOPS_EXEC:PMC0,UOPS_RETIRED_ALL:PMC1,UOPS_RETIRED_CORE_ALL:PMC2,UOPS_RETIRED_RETIRE_SLOTS:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS50  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS51=(
UOPS_RETIRED_CORE_RETIRE_SLOTS:PMC0,UOPS_RETIRED_USED_CYCLES:PMC1,UOPS_RETIRED_STALL_CYCLES:PMC2,UOPS_RETIRED_TOTAL_CYCLES:PMC3
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS51  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

LIKWID_PERF_EVENTS52=(
UOPS_RETIRED_CORE_USED_CYCLES:PMC0,UOPS_RETIRED_CORE_STALL_CYCLES:PMC1,UOPS_RETIRED_CORE_TOTAL_CYCLES:PMC2
)
likwid-perfctr -f -C S0:0-11,24-35@S1:12-23,36-47 -g $LIKWID_PERF_EVENTS52  $EXE >> output_${BENCHMARKS[$BCOUNT]}_$ACOUNT

done
done